In [1]:
import numpy as np

In [2]:
# Part 1
num = 20
y_hat = np.linspace(-1,1, num)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [3]:
y = np.linspace(0,1, num)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
#shapes and dimensions of y & y-hat
y_hat.shape

(20,)

In [5]:
y.shape

(20,)

In [6]:
y_hat.ndim

1

In [7]:
y.ndim

1

In [8]:
# Mean Squared Error
summ = 0
for i in range (num):
    eq = (y_hat[i]-y[i])**2
    summ += eq
L = summ/num
L

0.34210526315789475

In [9]:
#Mean Absolute Error
summ = 0
for i in range (num):
    eq = np.absolute(y_hat[i]-y[i])
    summ += eq
L = summ/num
L

0.5000000000000001

In [10]:
#Mean Squared Log Error

summ = 0
for i in range (num):
    eq = (np.log(y_hat[i]+1) - np.log(y[i]+1))**2
    summ += eq
L = summ/num
L

C:\Users\airco\AppData\Local\Temp\ipykernel_10760\2737708436.py:5: RuntimeWarning: divide by zero encountered in log
  eq = (np.log(y_hat[i]+1) - np.log(y[i]+1))**2


inf

In [11]:
#Mean Absolute Percentage Error

summ = 0
for i in range (num):
    eq = np.absolute((y_hat[i]-y[i])/y[i])
    summ += eq
L =(0.100*summ)/num
L

C:\Users\airco\AppData\Local\Temp\ipykernel_10760\3750901990.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  eq = np.absolute((y_hat[i]-y[i])/y[i])


inf

In [12]:
# Part 2
# 1.
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# 2.
N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
# 3.
N[1,:]

array([5, 6, 7, 8])

In [15]:
# 4.
np.min(N, axis=0)

array([1, 2, 3, 4])

In [16]:
# 5. 
np.argmin(N, axis=0)

array([0, 0, 0, 0], dtype=int64)

In [17]:
# 6.
N.mean()

8.5

In [18]:
# 7. Vector
V = np.ones(4, dtype='int32')
V

array([1, 1, 1, 1])

In [19]:
# 8.
np.dot(N,V)

array([10, 26, 42, 58])